- app/Http/Controllers/ParticipantController.php
- app/Http/Controllers/VerificationController.php
- app/Mail/emailVerificationResponse.php
- app/Models/Participant.php
- package-lock.json
- resources/views/mails/emailVerificationResponse.blade.php
- resources/views/mails/signup.blade.php
- resources/views/signup.blade.php
Co-authored-by: Albion99 <Albion99@users.noreply.github.com>
Co-authored-by: SanneHermans <SanneHermans@users.noreply.github.com>
> Made email confirmation email

- routes/web.php
closes https://github.com/salvemundi/intro-application/issues/14
> switched routes

- app/Http/Controllers/VerificationController.php
- package-lock.json
- resources/views/include/navbarGuapp.blade.php
- resources/views/verifyResponse.blade.php
- routes/web.php
> email can now be verified once

- README.md
- composer.json
- composer.lock
- docker-compose.yml
- package-lock.json
> Added docker support

- app/Http/Controllers/APIController.php
- app/Http/Controllers/BlogController.php
- app/Http/Controllers/BusController.php
- app/Http/Controllers/DashboardController.php
- app/Http/Controllers/ParticipantController.php
- app/Http/Controllers/RegistrationController.php
- app/Models/Blog.php
- routes/web.php
> Updated path for all controllers and added blogs

- app/Http/Controllers/ConfirmationController.php
- app/Http/Controllers/PaymentController.php
- composer.lock
- resources/sass/app.scss
- resources/views/SuccessPage.blade.php
- resources/views/admin/registrations.blade.php
- resources/views/paymentFailed.blade.php
- resources/views/verifyResponse.blade.php
- routes/web.php
fixed bugs with payment system
> Fixing bugs

- app/Http/Controllers/BlogController.php
- app/Http/Controllers/ConfirmationController.php
- app/Http/Controllers/ParticipantController.php
- app/Http/Controllers/PaymentController.php
- app/Http/Controllers/VerificationController.php
- app/Http/Controllers/WebhookController.php
- app/Mail/emailPaymentSucceeded.php
- app/Mail/participantMail.php
- app/Models/Participant.php
- composer.lock
- database/migrations/2022_06_09_192419_update_content_table.php
- docker-compose.yml
- package-lock.json
- resources/sass/_variables.scss
- resources/sass/qr-code.scss
- resources/views/SuccessPage.blade.php
- resources/views/admin/blogInput.blade.php
- resources/views/admin/blogs.blade.php
- resources/views/admin/registrations.blade.php
- resources/views/blogs.blade.php
- resources/views/confirmSignup.blade.php
- resources/views/include/navbarGuapp.blade.php
- resources/views/mails/participantMail.blade.php
- resources/views/purpleSignup.blade.php
- resources/views/signup.blade.php
- resources/views/verifyResponse.blade.php
- routes/web.php
Closes #42 
Closes #34 
Closes #31 
Closes #3
> Add emails

- app/Http/Controllers/ParticipantController.php
- app/Mail/emailPaymentSucceeded.php
- database/migrations/2022_06_21_144359_add_note_to_participants_table.php
- database/migrations/2022_06_23_224114_add_removal_to_participants_table.php
- resources/views/admin/participants.blade.php
- resources/views/admin/qr.blade.php
- routes/web.php
> Add filter

- resources/views/admin/participants.blade.php
> Added verification column

- app/Http/Controllers/DashboardController.php
- app/Http/Controllers/PaymentController.php
- app/Http/Controllers/VerificationController.php
- resources/views/admin/dashboard.blade.php
> Fixed dashboard

- app/Models/Participant.php
- resources/views/admin/qr.blade.php
- routes/web.php
> Update checkin view

- app/Http/Controllers/ConfirmationController.php
- app/Http/Controllers/ParticipantController.php
- app/Http/Controllers/PaymentController.php
- app/Http/Controllers/VerificationController.php
- app/Mail/manuallyAddedMail.php
- resources/views/admin/addParticipants.blade.php
- resources/views/mails/emailManuallyAdded.blade.php
- routes/web.php
> Adding qr codes when adding participant

- app/Http/Controllers/ConfirmationController.php
- app/Mail/emailPaymentSucceeded.php
- app/Mail/resendQRCode.php
- composer.json
- composer.lock
- config/app.php
- resources/sass/participants.scss
- resources/views/admin/qr.blade.php
> Set white background qrcode

- app/Http/Controllers/ParticipantController.php
- app/Mail/emailConfirmationSignup.php
- resources/views/admin/participants.blade.php
- resources/views/include/participantConfirmationMailModal.blade.php
- routes/web.php
> Send confirmation to individual participants

- app/Mail/emailPaymentSucceeded.php
- app/Mail/manuallyAddedMail.php
- app/Mail/parentMailSignup.php
- app/Mail/resendQRCode.php
- resources/views/admin/qr.blade.php
> added torch functionality

- app/Http/Controllers/ParticipantController.php
- database/migrations/2022_07_31_161309_update_participants_purple_table.php
- resources/views/admin/participants.blade.php
existing purple participants can be registered manually by me. No further action required from then on.
> added purple filter

- app/Http/Controllers/DashboardController.php
> updated dashboard

- resources/views/mails/emailConfirmationResponse.blade.php
- resources/views/mails/emailManuallyAdded.blade.php
- resources/views/mails/emailPaymentSucceeded.blade.php
- resources/views/mails/emailResendVerification.blade.php
- resources/views/mails/emailVerificationResponse.blade.php
- resources/views/mails/parentSignup.blade.php
- resources/views/mails/participantMail.blade.php
- resources/views/mails/paymentFailed.blade.php
- resources/views/mails/resendQRcode.blade.php
- resources/views/mails/signup.blade.php
> updated emails

- resources/views/admin/participants.blade.php
> added fontys email search

- app/Http/Controllers/BlogController.php
- app/Http/Controllers/ParticipantController.php
- resources/views/admin/participants.blade.php
- resources/views/include/navbarGuapp.blade.php
- fixed days until intro count on blogs page
- moved participant id from bootstrap table to selected participant card
- changed navbar (home page, not admin)
- fixed participants days since signup count on admin page (or atleast it should be)
- removed verified from participants table in frontend
- changed checked in to a bootstrap pill (fancy colorsss)
> processed some feedback

- resources/sass/_variables.scss
- resources/sass/app.scss
- resources/sass/checkinQR.scss
- resources/sass/participants.scss
- resources/sass/sidebar.scss
- resources/views/admin/dashboard.blade.php
- resources/views/admin/qr.blade.php
- resources/views/include/sidebar.blade.php
- resources/views/signup.blade.php
Changelog:
- Changed logo in sidebar (admin page) to redirect to home page
- Changed spacing in signup form on landing page
- Prevented unneeded api requests on qr code incheck page
- Changed card and some minor layout changes on qr code incheck page
- Changed introduction date on landing page
- Clarified dashboard, did not change layout any further as I didn't find the feedback valid / concrete enough.
> Process feedback intro

- app/Exports/ExportPayment.php
- app/Exports/ParticipantsNotCheckedInExport.php
- app/Http/Controllers/APIController.php
- app/Http/Controllers/ParticipantController.php
- database/migrations/2023_06_29_132010_update_participants_table_removing_studentyear.php
- resources/views/admin/addParticipants.blade.php
- resources/views/admin/participantCheckedIn.blade.php
- resources/views/admin/participants.blade.php
- resources/views/confirmSignup.blade.php
- resources/views/purpleSignup.blade.php
- routes/web.php
- Added tooltips
- Added purple back and changed fontys email to any email
- Removed studentyear (with added migration)
- Removed fontysemail where needed
- Removed some regex in participantcontroller
Payments still work!
> Adding tooltips added purple back removing stuff

- app/Mail/emailPaymentSucceeded.php
- database/seeders/SettingsSeeder.php
- resources/views/mails/emailPaymentSucceeded.blade.php
- resources/views/shifts.blade.php
> updated email for confirmed signups
